### ISSUE TITLE
Guidance: Using Apple Metal GPU cores for multiprocessing

### ISSUE THREAD

**Issue by do-me** [ProteusMRIgHIFU/BabelViscoFDTD#10]
Hi folks, 

thanks for this extensive repository sharing your insights and experiences fine-tuning your code for different platforms!

I found this repo through the [apple forum](https://forums.developer.apple.com/forums/thread/698990) as I was looking for some guidance of how to best make use of all of my metal GPU cores for multiprocessing in Python (M3 max).

Do you have some ideas or even some sample code to as a starting point? I was surprised not to be able to find anything suitable for this purpose on GitHub apart from the ML community with PyTorch and Tensorflow. I am trying to get something like this running: https://github.com/rapidsai/cudf, so "simply" using the GPU cores to manipulate my pandas series in parallel. 

Sorry for opening an out-of-topic issue, but there are no discussions activated in this repo and I thought other people might land here too asking similar questions.

**Comment by spichardo** [comment]
Sorry I didn't see this until now. From my experience, there is no an easy straighforward formula to ensure good occupancy in Metal. CUDA has since some time a [function](https://developer.nvidia.com/blog/cuda-pro-tip-occupancy-api-simplifies-launch-configuration/) that helps to calculate the grid sizes for computing considering number of registers used in the kernel, but Metal has a more [generic](https://developer.apple.com/documentation/metal/compute_passes/calculating_threadgroup_and_grid_sizes) approach that does not take into account resources used by the kernel.

Other than starting with the recommended generic approach by the Apple documentation, it takes a bit of gputraces captures to measure the degree of occupancy of the GPU cores and find a calculation of grid+block sizes that ensure a good occupancy, and ultimately lower computing wall-time.
